import React, { useEffect, useState } from "react";
import {Text, View, TextInput, Image, FlatList } from "react-native";
import { styles }  from './styles';
import { SafeAreaView } from "react-native-safe-area-context";
import { colors } from "../../../utils/colors";

import AppHeader from "../../../components/AppHeader";

const PostData = [
    {id: '1'}, {id: '2'}, {id: '3'}, 
    {id: '4'}, {id: '5'}, {id: '6'}, 
]

const ForumHome = ({ navigation }) => {
    
    //navigations
    const onChat = () => {
        navigation.navigate('ForumAllChats');
    };
    const onBell = () => {
        navigation.navigate('Notifications');
    };

    //Reset the search bar?
    // useEffect(() => {
    //     onChange('search', "");
    // }, []);
    
    const [values, setValues] = useState({});
    // Adds to the value object
    const onChange = (key, value) => {
        setValues(v => ({...v, [key]: value}))
    } 

    const SearchBar = () => {
        return (
            <View style={styles.inputContainer}>
                <TextInput placeholder="Search post by title..." style={styles.input}
                    value={values.search} onChangeText={(v) => onChange('search', v)} />
                <Image style={styles.searchIcon} source={require('../../../assets/icons/search.png')}/>
            </View>
        )
    }

    const SortBar = () => {
        return (
            <View style={styles.sortContainer}>
                <Image style={styles.sortIcon} source={require('../../../assets/icons/team.png')}/>
                <Text style={{fontWeight: 500}}> New Posts </Text>
            </View>
        )
    }

    const renderPosts = ({item}) => {
        return (
            <View style={{backgroundColor: colors.white, height: 100, marginVertical: 16,}}>
                <Text>This is a Post generated by flatList</Text>
            </View>
        )
    };

    const Posts = () => {
        return (
            <FlatList data={PostData} keyExtractor={item => item.id} 
                renderItem={renderPosts}
            />
        )
    }

    return (
        <SafeAreaView style={styles.mainContainer}>
            <AppHeader title="Forum" showChat showBell onBell={onBell} onChat={onChat}/>
            {SearchBar()}
            {SortBar()}
            {Posts()}

        </SafeAreaView>
    )
}

export default React.memo(ForumHome);