export const defaultCategories = [{label: 'Add Category', value: 'Add', parent: 'Other', index: 19}, 
                                {label: 'Other Income', value: 'Other Income', parent: 'Income', index: 18},
                                {label: 'Allowance', value: 'Allowance', parent: 'Income', index: 17},
                                {label: 'Salary', value: 'Salary', parent: 'Income', index: 16},
                                {label: 'Fun Money', value: 'Fun Money', parent: 'Fun', index: 15},
                                {label: 'Hobbies', value: 'Hobbies', parent: 'Fun', index: 14},
                                {label: 'Entertainment', value: 'Entertainment', parent: 'Fun', index: 13},
                                {label: 'Gifts', value: 'Gifts', parent: 'Fun', index: 12},
                                {label: 'Fitness', value: 'Fitness', parent: 'Fun', index: 11},
                                {label: 'Other Expenses', value: 'Other Expenses', parent: 'General', index: 10},
                                {label: 'Personal Items', value: 'Personal Items', parent: 'General', index: 9},
                                {label: 'Pets', value: 'Pets', parent: 'General', index: 8},
                                {label: 'Education', value: 'Education', parent: 'General', index: 7},
                                {label: 'Insurance', value: 'Insurance', parent: 'General', index: 6},
                                {label: 'Medical Expense', value: 'Medical Expense', parent: 'General', index: 5},
                                {label: 'Utility bills', value: 'Utility bills', parent: 'Required', index: 4},
                                {label: 'Rentals', value: 'Rentals', parent: 'Required', index: 3},
                                {label: 'Transportation', value: 'Transportation', parent: 'Required', index: 2},
                                {label: 'Food & Beverage', value: 'Food & Beverage', parent: 'Required', index: 1}];